version: '3.8'

services:
  app:
    build: .
    ports:
      - "443:443"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - GOOGLE_CLIENT_KEY=${GOOGLE_CLIENT_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - COOKIE_PASS=${COOKIE_PASS}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - CSP_SEED=${CSP_SEED}
      - ISSUER_DID=${ISSUER_DID}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  pgdata:
